payload: # ДЛЯ ПРИЛОЖЕНИЙ/СЛУЖБ ANDROID и IPHONE
  - PROCESS-NAME,max
  - PROCESS-NAME,ru.max
  - PROCESS-NAME,max.ru
  - PROCESS-NAME,gosuslugi
  - PROCESS-NAME,gosuslugi.ru
  - PROCESS-NAME,ru.gosuslugi
  - PROCESS-NAME,club.skllzz.fitness
  - PROCESS-NAME,com.apegroup.mcdonaldsrussia
  - PROCESS-NAME,com.bankffin.portfolio
  - PROCESS-NAME,com.bastion
  - PROCESS-NAME,com.bifit.rncbbeta
  - PROCESS-NAME,ru.spb.parking
  - PROCESS-NAME,com.whsd.whsdapp
  - PROCESS-NAME,com.orgp.spbpodorozhnik
  - PROCESS-NAME,ru.ftc.tc
  - PROCESS-NAME,com.carshering
  - PROCESS-NAME,com.citymobil
  - PROCESS-NAME,com.taxsee.taxsee
  - PROCESS-NAME,ru.yandex.uber
  - PROCESS-NAME,ru.taxovichkof.android
  - PROCESS-NAME,ru.rolf.rolf
  - PROCESS-NAME,ru.russianhighways.mobile
  - PROCESS-NAME,ru.mosparking.appnew
  - PROCESS-NAME,centrida.neftmagistral
  - PROCESS-NAME,ru.pichesky.rosneft
  - PROCESS-NAME,ru.serebryakovas.lukoilmobileapp
  - PROCESS-NAME,ru.tatneft.gasstations
  - PROCESS-NAME,com.gpn.azs
  - PROCESS-NAME,com.coolclever.app
  - PROCESS-NAME,com.deliveryclub
  - PROCESS-NAME,com.discover.moscow.lite
  - PROCESS-NAME,com.edadeal.android
  - PROCESS-NAME,com.gnivts.ausn
  - PROCESS-NAME,com.gnivts.selfemployed
  - PROCESS-NAME,com.icemobile.lenta.prod
  - PROCESS-NAME,com.idamob.tinkoff.android
  - PROCESS-NAME,com.keenetic.kn
  - PROCESS-NAME,ru.netcraze.app
  - PROCESS-NAME,com.moscowsport
  - PROCESS-NAME,com.premiumbonus.jamm.ramen
  - PROCESS-NAME,pro.arora.mobile.pizza_milana
  - PROCESS-NAME,pro.arora.mobile.maradi
  - PROCESS-NAME,com.punicapp.whoosh
  - PROCESS-NAME,com.ru.dixy
  - PROCESS-NAME,com.salute.smarthome.prod
  - PROCESS-NAME,com.sberauto.mobile
  - PROCESS-NAME,com.sberbank.sberpravo
  - PROCESS-NAME,com.tdm.messenger
  - PROCESS-NAME,com.tjuraniaapp
  - PROCESS-NAME,com.uip.gosuslugi2
  - PROCESS-NAME,com.vk.clips
  - PROCESS-NAME,live.vkplay.app
  - PROCESS-NAME,ru.mail.mailapp
  - PROCESS-NAME,com.vk.im
  - PROCESS-NAME,com.vk.vkvideo
  - PROCESS-NAME,com.wildberries.ru
  - PROCESS-NAME,com.yandex.bank
  - PROCESS-NAME,com.yandex.bluecollars
  - PROCESS-NAME,com.yandex.iot
  - PROCESS-NAME,com.yandex.lavka
  - PROCESS-NAME,com.yandex.mobile.drive
  - PROCESS-NAME,com.yandex.mobile.realty
  - PROCESS-NAME,com.yandex.plus.game.city
  - PROCESS-NAME,com.yandex.searchapp
  - PROCESS-NAME,com.yandex.shedevrus2
  - PROCESS-NAME,com.yandex.tasks.androidapp
  - PROCESS-NAME,com.yandex.yamb
  - PROCESS-NAME,com.zvooq.openplay
  - PROCESS-NAME,es.hol.ing.zagsr
  - PROCESS-NAME,im.dlg.dialogx
  - PROCESS-NAME,im.dlg.enterprise
  - PROCESS-NAME,io.github.dovecoteescapee.byedpi
  - PROCESS-NAME,io.itforces.android.timetable
  - PROCESS-NAME,logo.com.mbanking
  - PROCESS-NAME,org.orange.mobile
  - PROCESS-NAME,pro.sber_zvuk
  - PROCESS-NAME,ru.akbars.mobile
  - PROCESS-NAME,ru.alfabank.mobile.android
  - PROCESS-NAME,ru.alfabank.oavdo.amc
  - PROCESS-NAME,ru.alfadirect.app
  - PROCESS-NAME,ru.aliexpress.buyer
  - PROCESS-NAME,ru.altarix.mos.pgu
  - PROCESS-NAME,ru.auto.ara
  - PROCESS-NAME,ru.aviasales
  - PROCESS-NAME,ru.beru.android
  - PROCESS-NAME,ru.bspb
  - PROCESS-NAME,ru.burgerking
  - PROCESS-NAME,ru.cardsmobile.mw3
  - PROCESS-NAME,ru.crptech.b2bmark
  - PROCESS-NAME,ru.crptech.mark
  - PROCESS-NAME,ru.datapax.mosobl
  - PROCESS-NAME,ru.diftechsvc
  - PROCESS-NAME,ru.dit.smartstaff
  - PROCESS-NAME,ru.dodopizza.app
  - PROCESS-NAME,ru.domclick.mortgage
  - PROCESS-NAME,ru.drclinics.app.sovcom
  - PROCESS-NAME,ru.dublgis.dgismobile
  - PROCESS-NAME,ru.dublgis.dgismobile4preview
  - PROCESS-NAME,otello.dgis.ru
  - PROCESS-NAME,ru.fanid
  - PROCESS-NAME,ru.filit.mvideo.b2c
  - PROCESS-NAME,ru.finassist
  - PROCESS-NAME,ru.fns.billchecker
  - PROCESS-NAME,ru.fns.billchecker.mobile.android
  - PROCESS-NAME,ru.fns.lkfl
  - PROCESS-NAME,ru.foodfox.client
  - PROCESS-NAME,ru.gazprombank.android.mobilebank.app
  - PROCESS-NAME,ru.getpharma.eapteka
  - PROCESS-NAME,ru.gnivc.lkip
  - PROCESS-NAME,ru.goods.marketplace
  - PROCESS-NAME,ru.gosuslugi.auto
  - PROCESS-NAME,ru.gosuslugi.culture
  - PROCESS-NAME,ru.gosuslugi.goskey
  - PROCESS-NAME,ru.gosuslugi.pos
  - PROCESS-NAME,ru.gosuslugi.pos.executor
  - PROCESS-NAME,ru.instamart
  - PROCESS-NAME,ru.kfc.kfc_delivery
  - PROCESS-NAME,ru.kinopoisk
  - PROCESS-NAME,ru.letobank.prometheus
  - PROCESS-NAME,ru.megafon.mlk
  - PROCESS-NAME,ru.megamarket.marketplace
  - PROCESS-NAME,ru.mes.sputnik
  - PROCESS-NAME,ru.mes.dnevnik
  - PROCESS-NAME,ru.more.play
  - PROCESS-NAME,ru.mos.app
  - PROCESS-NAME,ru.mos.ed
  - PROCESS-NAME,ru.mos.gz
  - PROCESS-NAME,ru.mos.myid
  - PROCESS-NAME,ru.mos.ourcity
  - PROCESS-NAME,ru.mos.polls
  - PROCESS-NAME,ru.mos.um
  - PROCESS-NAME,ru.mos.zaryadye
  - PROCESS-NAME,ru.mosgorpass
  - PROCESS-NAME,ru.mosmetro.metro
  - PROCESS-NAME,ru.mosoblgaz
  - PROCESS-NAME,ru.mosreg.easuz.portal
  - PROCESS-NAME,ru.mosreg.ekjp
  - PROCESS-NAME,ru.mosreg.mingos.mdp.app
  - PROCESS-NAME,ru.mosreg.mo112
  - PROCESS-NAME,ru.mosreg.uslugi.mobile.beta
  - PROCESS-NAME,ru.mts.bank
  - PROCESS-NAME,ru.mts.mtstv
  - PROCESS-NAME,ru.mts.mymts
  - PROCESS-NAME,ru.mvm.eldo
  - PROCESS-NAME,ru.sportmaster.app
  - PROCESS-NAME,ru.myspar
  - PROCESS-NAME,ru.nalog.rmr.client
  - PROCESS-NAME,ru.nspk.mir.loyalty
  - PROCESS-NAME,ru.nspk.mirpay
  - PROCESS-NAME,ru.okbmei.gosservice
  - PROCESS-NAME,ru.ostrovok.android
  - PROCESS-NAME,ru.ozon.app.android
  - PROCESS-NAME,ru.ozon.fintech.finance
  - PROCESS-NAME,ru.perekrestok.app
  - PROCESS-NAME,club.chizhik
  - PROCESS-NAME,ru.plus.bookmate
  - PROCESS-NAME,ru.pyaterochka.app.browser
  - PROCESS-NAME,ru.raiffeisennews
  - PROCESS-NAME,ru.rambler.mail
  - PROCESS-NAME,ru.rostel
  - PROCESS-NAME,ru.rutube.app
  - PROCESS-NAME,ru.rutube.RutubeKids
  - PROCESS-NAME,ru.rutube.studio
  - PROCESS-NAME,ru.rutube.app.tv
  - PROCESS-NAME,gpm.tnt_premier
  - PROCESS-NAME,one.premier.rustoretv
  - PROCESS-NAME,ru.rzd.pass
  - PROCESS-NAME,ru.salute.b2b.prod
  - PROCESS-NAME,ru.sbcs.store
  - PROCESS-NAME,ru.sber.csradar
  - PROCESS-NAME,ru.sber.telecom
  - PROCESS-NAME,ru.sberbank.investor
  - PROCESS-NAME,ru.sberbank.onlineencashment
  - PROCESS-NAME,ru.sberbank.sberkids
  - PROCESS-NAME,ru.sberbank.sbersign
  - PROCESS-NAME,ru.sberbank_sbbol
  - PROCESS-NAME,ru.sberbankmobile
  - PROCESS-NAME,ru.sberins.insureapp.android
  - PROCESS-NAME,ru.sbermegamarket.pro
  - PROCESS-NAME,ru.sovcombank.dms
  - PROCESS-NAME,ru.sovcombank.investor
  - PROCESS-NAME,ru.sovcomcard.halva.v1
  - PROCESS-NAME,pro.rocketTech.rocket.rocketapp
  - PROCESS-NAME,ru.oneme.app
  - PROCESS-NAME,ru.start.androidmobile
  - PROCESS-NAME,ru.bristol.bristol_app
  - PROCESS-NAME,www.metro.com
  - PROCESS-NAME,ru.tander.magnit
  - PROCESS-NAME,ru.technokad.digitalkey
  - PROCESS-NAME,ru.tii.lkcomu
  - PROCESS-NAME,ru.tinkoff.bnpl
  - PROCESS-NAME,ru.tinkoff.invest.course
  - PROCESS-NAME,ru.tinkoff.investing
  - PROCESS-NAME,ru.tinkoff.magent
  - PROCESS-NAME,ru.tinkoff.mvno
  - PROCESS-NAME,ru.tinkoff.posterminal
  - PROCESS-NAME,ru.tinkoff.sme
  - PROCESS-NAME,ru.troika.regional
  - PROCESS-NAME,ru.urentbike.app
  - PROCESS-NAME,com.vkontakte.android
  - PROCESS-NAME,ru.vk.store
  - PROCESS-NAME,ru.vk.video
  - PROCESS-NAME,ru.vkmusic.audio
  - PROCESS-NAME,ru.tbank.online
  - PROCESS-NAME,ru.amina.moscow
  - PROCESS-NAME,ru.lewis.dbo
  - PROCESS-NAME,ru.gibdd_pay.app
  - PROCESS-NAME,com.moex.finuslugi
  - PROCESS-NAME,su.azure.paymaster
  - PROCESS-NAME,ru.nspk.sbpay
  - PROCESS-NAME,ru.gosuslugi.school
  - PROCESS-NAME,ru.sigma.gisgkh
  - PROCESS-NAME,ru.rshb.dbo
  - PROCESS-NAME,ru.spb.iac.dnevnikspb_new
  - PROCESS-NAME,ru.ues.users_personal_account
  - PROCESS-NAME,com.leroymerlin.mobile
  - PROCESS-NAME,ru.kari.android
  - PROCESS-NAME,ru.sunlight.sunlight
  - PROCESS-NAME,level.travel
  - PROCESS-NAME,ru.abrr.gas
  - PROCESS-NAME,com.maxxt.recordradio
  - PROCESS-NAME,com.uchi.app
  - PROCESS-NAME,ru.chitaigorod.mobile
  - PROCESS-NAME,ru.usetech.velobike.v2
  - PROCESS-NAME,ru.zolotoy585.customer
  - PROCESS-NAME,com.onecwearable.keyboard.rustore
  - PROCESS-NAME,com.gloriajeans.mobile
  - PROCESS-NAME,ru.rabota.app2
  - PROCESS-NAME,ru.domopult.mosobleirc.android
  - PROCESS-NAME,ru.rgs.lk
  - PROCESS-NAME,ru.dikidi
  - PROCESS-NAME,ru.citilink
  - PROCESS-NAME,ru.spb.dnevnik
  - PROCESS-NAME,ru.sima_land.spb.market
  - PROCESS-NAME,ru.ufanet.myufanet
  - PROCESS-NAME,ru.bcs.bcsbank
  - PROCESS-NAME,com.svoi.bank
  - PROCESS-NAME,ru.vkusvill
  - PROCESS-NAME,ru.detmir.dmbonus
  - PROCESS-NAME,ru.lenta.lentochka
  - PROCESS-NAME,goldapple.ru.goldapple.customers
  - PROCESS-NAME,com.notissimus.allinstruments.android
  - PROCESS-NAME,ru.vseapteki
  - PROCESS-NAME,ru.leonardo.leonardoshop
  - PROCESS-NAME,ru.leroymerlin.mobile
  - PROCESS-NAME,ru.maxidom.ecomm
  - PROCESS-NAME,air.ru.obi.mobile
  - PROCESS-NAME,com.logistic.sdek
  - PROCESS-NAME,ru.vtb24.mobilebanking.android
  - PROCESS-NAME,ru.yandex.androidkeyboard
  - PROCESS-NAME,ru.yandex.disk
  - PROCESS-NAME,ru.yandex.games
  - PROCESS-NAME,ru.yandex.key
  - PROCESS-NAME,ru.yandex.mail
  - PROCESS-NAME,ru.yandex.market.partner
  - PROCESS-NAME,ru.yandex.metro
  - PROCESS-NAME,ru.yandex.mobile.gasstations
  - PROCESS-NAME,ru.yandex.music
  - PROCESS-NAME,ru.yandex.practicum.flutter_practicum
  - PROCESS-NAME,ru.yandex.subtitles
  - PROCESS-NAME,ru.yandex.taxi
  - PROCESS-NAME,ru.yandex.taximeter
  - PROCESS-NAME,ru.yandex.translate
  - PROCESS-NAME,ru.yandex.travel
  - PROCESS-NAME,ru.yandex.weatherplugin
  - PROCESS-NAME,ru.yandex.yandexmaps
  - PROCESS-NAME,ru.yandex.yandexnavi
  - PROCESS-NAME,ru.yandex_team.calendar_app
  - PROCESS-NAME,ru.yoo.business
  - PROCESS-NAME,ru.yoo.kassa
  - PROCESS-NAME,ru.yoo.money
  - PROCESS-NAME,ru.yoo.sdk.kassa.payments.example.release
  - PROCESS-NAME,ru.yota.android
  - PROCESS-NAME,ru.zhuck.webapp
  - PROCESS-NAME,ru.ok.android
  - PROCESS-NAME,team.rtds.checkcontrol
  - PROCESS-NAME,tv.lfstrm.smotreshka
  - PROCESS-NAME,com.apteka.sklad
  - PROCESS-NAME,com.platfomni.gorzdrav
  - PROCESS-NAME,com.invitro.app
  - PROCESS-NAME,youdrive.today
  - PROCESS-NAME,com.kms.free
  - PROCESS-NAME,ru.paribet
  - PROCESS-NAME,ru.rosbank.android.beta
  - PROCESS-NAME,ru.beeline.services
  - PROCESS-NAME,ru.beeline.cloud
  - PROCESS-NAME,ru.beeline.tve.android
  - PROCESS-NAME,ru.otpbank.mobile
  - PROCESS-NAME,biz.growapp.winline
  - PROCESS-NAME,com.national.lottery
  - PROCESS-NAME,ru.stoloto.mobile
  - PROCESS-NAME,ru.bkfon
  - PROCESS-NAME,ru.cian.main
  - PROCESS-NAME,ru.m2.squaremeter
  - PROCESS-NAME,ru.winelab
  - PROCESS-NAME,ru.smmd.superdelivery
  - PROCESS-NAME,ru.aisa.android.ekpv2
  - PROCESS-NAME,com.mobium12580.app
  - PROCESS-NAME,ru.smclinic.app.lk
  - PROCESS-NAME,com.teremok.keys
  - PROCESS-NAME,ru.tokyocity.tokyocity
  - PROCESS-NAME,com.tseh85
  - PROCESS-NAME,ru.plazius.cofix
  - PROCESS-NAME,com.avito.android
  - PROCESS-NAME,ru.x5.omni
  - PROCESS-NAME,ru.tele2.mytele2
  - PROCESS-NAME,by.advasoft.android.troika.app
  - PROCESS-NAME,com.octopod.russianpost.client.android
  - PROCESS-NAME,ru.dahl.messenger
  - PROCESS-NAME,ru.dns.shop.android