payload: # Этим показываем свой русский-реальный IP 
  - DOMAIN-SUFFIX,2ip.ru
  - DOMAIN-SUFFIX,max.ru
  - DOMAIN-SUFFIX,yastatic.net
  - DOMAIN-SUFFIX,ya.ruhttps://max.ru/
  - DOMAIN-SUFFIX,yandex.net
  - DOMAIN-SUFFIX,yandex.kz
  - DOMAIN-SUFFIX,yandex.com
  - DOMAIN-SUFFIX,yadi.sk
  - DOMAIN-SUFFIX,mycdn.me
  - DOMAIN-SUFFIX,jivosite.com
  - DOMAIN-SUFFIX,vk.com
  - DOMAIN-SUFFIX,vk.ru
  - DOMAIN-SUFFIX,avira.com
  - DOMAIN-SUFFIX,.ru
  - DOMAIN-SUFFIX,.su
  - DOMAIN-SUFFIX,.by
  - DOMAIN-SUFFIX,.ru.com
  - DOMAIN-SUFFIX,.ru.net
  - DOMAIN-SUFFIX,kudago.com
  - DOMAIN-SUFFIX,kinescope.io
  - DOMAIN-SUFFIX,redheadsound.studio
  - DOMAIN-SUFFIX,plplayer.online
  - DOMAIN-SUFFIX,lomont.site
  - DOMAIN-SUFFIX,remanga.org
  - DOMAIN-SUFFIX,shopstory.live
  - DOMAIN-SUFFIX,vkvideo.ru
  - DOMAIN-SUFFIX,live.vkvideo.ru
  - DOMAIN-SUFFIX,sasflix.ru
  - DOMAIN-SUFFIX,boosty.to
  - DOMAIN-SUFFIX,gosuslugi.ru
  - DOMAIN-KEYWORD,gosuslugi
  - DOMAIN-KEYWORD,tbank
  - DOMAIN-KEYWORD,sber
  - DOMAIN-KEYWORD,sberbank
  - DOMAIN-KEYWORD,vtb
  - DOMAIN-KEYWORD,rut-miit
  - DOMAIN-KEYWORD,miit
  - DOMAIN-KEYWORD,avito
  - DOMAIN-KEYWORD,hh
  - DOMAIN-KEYWORD,miradres
  - DOMAIN-KEYWORD,kinopoisk
  - DOMAIN-KEYWORD,premier
  - DOMAIN-KEYWORD,shutterstock
  - DOMAIN-KEYWORD,2gis
  - DOMAIN-KEYWORD,diginetica
  - DOMAIN-KEYWORD,kinescopecdn
  - DOMAIN-KEYWORD,researchgate
  - DOMAIN-KEYWORD,springer
  - DOMAIN-KEYWORD,nextcloud
  - DOMAIN-KEYWORD,kaspersky
  - DOMAIN-KEYWORD,stepik
  - DOMAIN-KEYWORD,likee
  - DOMAIN-KEYWORD,snapchat
  - DOMAIN-KEYWORD,yappy
  - DOMAIN-KEYWORD,max
  - DOMAIN-KEYWORD,pikabu
  - DOMAIN-KEYWORD,okko
  - DOMAIN-KEYWORD,wink
  - DOMAIN-KEYWORD,kion
  - DOMAIN-KEYWORD,ozon
  - DOMAIN-KEYWORD,wildberries
  - DOMAIN-KEYWORD,aliexpress
